name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # needed for progressive mode to work
            
    - name: Install Ansible Azure
      run: |
        pip install -U pip setuptools
        pip install 'ansible[azure]'
      
    - name: Login via Az module
      uses: azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
            
    - name: Run Ansible Playbook
      run: ansible-playbook create-aks.yaml -vvv --extra-vars "ssh_key='${{ secrets.SSH_KEY }}' client_id=${{ secrets.CLIENT_ID }} client_secret=${{ secrets.CLIENT_SECRET }}"
