# This is a basic workflow that is manually triggered

name: Manual AKS cluster deploy

# This is a private excercise to use GitHub Actions to deploy a AKS cluster.
# Based on MS-Learn: Exercise - Create an Azure Kubernetes Service cluster
# https://learn.microsoft.com/en-gb/training/modules/aks-deploy-container-app/3-exercise-create-aks-cluster

# This will create: 
# 1 AKS cluster 
# 2 nodes - System mode - node-vm-size Standard_B2s
# 2 nodes - User mode  - node-vm-size Standard_B2s
# 1 registry attached to the cluster
on:
  workflow_dispatch:

# Env to set reusable variables
env:
  RGNAME: rg-k8s-test # A pre created resourcegroup: az group create --name=$RESOURCE_GROUP --location=$LOCATION
  ACRNAME: acr-k8s-test
  AKSNAME: aks-k8s-test

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single  job called Platform to create the AKS Cluster
  Platform:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git checkout
        uses: actions/checkout@v2

      - name: az CLI login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: AZ AKS Create
        run: az aks create --resource-group $RGNAME --name $AKSNAME --node-count 2 --enable-addons http_application_routing --generate-ssh-keys --node-vm-size Standard_B2s --network-plugin azure
      - name: AZ AKS Nodepool Add
        run: az aks nodepool add --resource-group $RGNAME --cluster-name $AKSNAME --name userpool --node-count 2 --node-vm-size Standard_B2s
      # Manually Create a Service Principal and configure Github Actions to use sp to connect to Subscription.
      - name: Az ACR Create
        run: az acr create -n $ACRNAME -g $RGNAME -l northeurope --sku Basic
      - name: Az ACR attach to AKS
        run: az aks update -n $AKSNAME -g $RGNAME --attach-acr $ACRNAME
